Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.100.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.provision "file", source: "app", destination: "/home/vagrant/app"
  config.vm.provision "file", source: "app.service", destination: "/home/vagrant/app.service"
  config.vm.provision "shell", inline: "sudo mv /home/vagrant/app.service /lib/systemd/system/app.service", run: "always"
  config.vm.provision "shell", inline: "sudo service app start", run: "always"
end
